(define (make-account balance password)
  (let ((guesses 0))
    ((lambda () (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (call-the-cops)
    (error "Hello? 999!"))
  (define (dispatch pw m)
  (if (eq? pw password)
    (set! guesses 0)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT"
                       m)))
    (lambda () (
        (error "Incorrect password")
        (if (eq? guesses 7) 
          (call-the-cops)
          (set! guesses (+ 1 guesses)))
    ))))
  dispatch))))

(define acc (make-account 100 'secret-password))
((acc 'wrong-password 'withdraw) 80)
